---
- name: Change MySQL root password on Percona Server
  hosts: percona_servers
  become: yes
  tasks:

    - name: Get MySQL temporary root password from the log file
      shell: "grep 'temporary password' /var/log/mysqld.log | awk '{print $NF}'"
      register: temp_password
      ignore_errors: yes

    - name: Debug the temporary password (optional, for troubleshooting)
      debug:
        msg: "Temporary MySQL root password is: {{ temp_password.stdout }}"

    - name: Change MySQL root password
      mysql_user:
        name: root
        password: "test1234"
        login_password: "{{ temp_password.stdout }}"
        check_implicit_admin: yes
      when: temp_password.stdout != ""
      ignore_errors: yes

    - name: Ensure MySQL root password is changed
      command: mysqladmin -u root -p'test1234' password 'test1234'
      when: temp_password.stdout != ""
      ignore_errors: yes

